sudo: required
services:
  - docker

before_install:
  # Use Dockerfile.dev to get access to source to run tests.
  # We only use client here because that's the only one with tests,
  # but we could do the same for server and worker.
  - docker build -t mriedem/react-test -f ./client/Dockerfile.dev ./client

script:
  # Run the container we just built using the tag, overwrite the command
  # to be "npm test" and pass the CI=true environment variable.
  - docker run -e CI=true mriedem/react-test npm test

after_success:
  # Build production version of all projects.
  - docker build -t mriedem/multi-client ./client
  - docker build -t mriedem/multi-nginx ./nginx
  - docker build -t mriedem/multi-server ./server
  - docker build -t mriedem/multi-worker ./worker
  # Log in to the docker CLI using env vars stored in travis CI project
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push mriedem/multi-client
  - docker push mriedem/multi-nginx
  - docker push mriedem/multi-server
  - docker push mriedem/multi-worker